<img src="img2/Banner Curso 1_.jpg" width="921" height="89" align="center"/>

<h1><center>Introducción a la ciencia de datos con Python - AnáhuacX</center></h1>
<h2><center>Actividad 2</center></h2>

La pobreza es un tema de suma relevancia para la agenda de todos los gobiernos alrededor del mundo. Los esfuerzos de múltiples naciones se han consolidado en los __Objetivos de Desarrollo Sostenible__ propuestos por la ONU, organización de la que México y muchos países de latinoamérica forman parte. Conocer la magnitud del problema es prioridad en orden para proponer intervenciones eficaces que abonen a disminuir la brecha de desigualdad.

<img src="img2/S-SDG-Poster_-Letter.jpg" width="800" height="800" align="center"/>

__En la siguiente actividad limpiarás y explorarás un dataframe en el que encontrarás datos relevantes al análisis de la pobreza en los diferentes países que integran a la Organización de las Naciones Unidas.__

<br>
<br>
<br>


1. Importa las librerías de Pandas, Numpy, Requests, Webbrowser y Beautiful soup a tu libreta. Las estaremos utilizando a lo largo del ejercicio.

In [1]:
# source ./venv/bin/activate # Para activar mi ambiente virtual en terminal

import pandas as pd
import numpy as np


2. Accede a la siguiente página web desde tu libreta utilizando webbrowser. 

_https://en.wikipedia.org/wiki/List_of_countries_by_percentage_of_population_living_in_poverty_

In [2]:
import webbrowser
# url_new = 'ttps://en.wikipedia.org/wiki/List_of_countries_by_percentage_of_population_living_in_poverty'
url = "https://en.wikipedia.org/w/index.php?title=List_of_countries_by_percentage_of_population_living_in_poverty&oldid=1151917193"
webbrowser.open(url)

True

3. Descarga en tu libreta la página proporcionada y obtén todas las tablas utilizando la librería requests y beautiful soup. Recuerda escribir el número de tabla correcto. Te recomendamos explorar la página.

In [4]:
import requests
res = requests.get(url)
# La liga en la que se basa el ejercicio es:
# https://en.wikipedia.org/w/index.php?title=List_of_countries_by_percentage_of_population_living_in_poverty&oldid=1151917193
# La versión viejita
res.text

'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>List of countries by percentage of population living in poverty - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 v

In [5]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(res.content)
table = soup.find_all('table')
table

[<table class="box-Update plainlinks metadata ambox ambox-content ambox-Update" role="presentation"><tbody><tr><td class="mbox-image"><div class="mbox-image-div"><span typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="290" data-file-width="360" decoding="async" height="34" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Ambox_current_red_Americas.svg/60px-Ambox_current_red_Americas.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/53/Ambox_current_red_Americas.svg/120px-Ambox_current_red_Americas.svg.png 1.5x" width="42"/></span></span></div></td><td class="mbox-text"><div class="mbox-text-span">This article needs to be <b>updated</b>.<span class="hide-when-compact"> Please help update this article to reflect recent events or newly available information.</span> <span class="date-container"><i>(<span class="date">September 2022</span>)</i></span></div></td></tr></tbody></table>,
 <table>
 <caption>
 </caption>
 <tbody><tr>
 <th data-so

4. Utilizando la función “read_html” de la librería “Pandas” guarda la tabla __"Percent of population (including non-citizens) living under \\$1,90, \\$3,20 and \\$5,50 a day"__ en una variable llamada “df”. 

_Sugerencia: Ocupa la función "head" de la librería "Pandas" para mostrar los primeros cinco elementos y verificar que haya funcionado lo anterior._

In [16]:
# pandas puede leer informaci´øn directamente de una URL
# sin usar requests y BeautifulSoup.
# Y quedo identica la tabla
# 
# Mejoras por otros compañeros

#tablas = pd.read_html(url)

#print(f"Se han encontrado {len(tablas)} tablas en la página.")

#if len(tablas) > 1:  
#    df = tablas[0]  
#    print("Tabla número 2 guardada en la variable 'df':")
#else:
#    print("No hay suficientes tablas en la página.")

#df.head()  # Muestra las primeras 5 filas de la tabla para verificar    

In [13]:
# OBSERVACION: La tabla actualmente maneja los valores de $2.15 \ 3.65 \ 6.85 a day
#               porque se han actualizdo. Y nos dan la siguiente nota aclaratoria:
#
#               "As a result of the adoption of the 2017 PPPs, the global poverty 
#                lines have been revised in 2022: The international poverty line, used
#                to define extreme global poverty, was revised to US$2.15 from US$1.90.
#                Poverty lines for other sets of countries have also been revised 
#                upwards. The poverty line for lower middle-income countries (LMICs)
#                has moved to US$3.65 from US$3.20, while the poverty line for upper
#                middle-income countries (UMICs) has moved to US$6.85 from US$5.50."
#
#               "The first table lists countries by the percentage of their population
#                with an income of less than $2.15 (the extreme poverty line), $3.65
#                and $6.85 US dollars a day in 2017 international PPP prices. The data
#                is from the most recent year available from the World Bank API" 
#
df = pd.read_html(url) #str(table))
df = df[1]

In [14]:
# OBSERVACION: Nos da 3 veces el encabezado por el formato de la tabla HTML, pero 
#               es el encabezado, no son filas

df.head()
df[0:4]

Country < $1.90[1][5] < $3.20[6] < $5.50[7]  Year      Continent  \
0    Albania        10.00%     26.60%     38.40%  2019         Europe   
1    Algeria         0.32%      2.23%     20.83%  2019         Africa   
2     Angola        51.40%     72.79%     89.13%  2019         Africa   
3  Argentina         1.60%      5.80%     18.20%  2020  South America   

   Unnamed: 6  
0         NaN  
1         NaN  
2         NaN  
3         NaN

5. __¿Cuántas filas tiene el dataframe?__ Recuerda utilizar tu libreta de Python para encontrar la respuesta.

166 FILAS

6. __¿Cuántas columnas posee el dataframe?__

7 COLUMNAS

In [19]:
df.shape

(166, 7)

7.	Debido a que los datos de la tabla contienen registros vacíos y el símbolo de porcentaje, es necesario que realices una limpieza de estos datos; utiliza las funciones __"replace"__ y __"dropna"__ de "Pandas" para lograrlo. 

__Ejemplo de sintaxis de la función "replace": df = df.replace({'%':""}, regex = True).__ (Se sugiere utilizar la función "head" con la tabla  modificada para visualizar que todo se encuentre en orden).

__¿Cuántas filas quedaron después de hacer esto?__

128 FILAS

In [29]:
df = df.replace({'%':""}, regex = True)
print(df.shape)
#df = df.drop('Unnamed: 6', axis=1)
df.head(166)
df_1 = df.dropna() 
print(df_1.head())
print(df_1.shape)

(166, 6)
     Country < $1.90[1][5] < $3.20[6] < $5.50[7]  Year      Continent
0    Albania         10.00      26.60      38.40  2019         Europe
1    Algeria          0.32       2.23      20.83  2019         Africa
2     Angola         51.40      72.79      89.13  2019         Africa
3  Argentina          1.60       5.80      18.20  2020  South America
4    Armenia          0.40       6.90      44.70  2020           Asia
(166, 6)


In [30]:
df_1.shape

(166, 6)

8.	Verifica el tipo de datos que poseen las columnas de tu dataframe utilizando la función __“info”__. (Puedes encontrar más información acerca de cómo utilizar esta función a través del siguiente link: https://www.geeksforgeeks.org/python-pandas-dataframe-info/ 

__¿Cuál es el tipo de datos que aparece en la mayoría de las columnas?__

OBJECT

In [32]:
##df_1.dtypes # Nos da los tipos de cada columna

## Renombramos las columnas, para poder trabajar con ellas, y 
## para que sea más clara la información
df_1.columns = ["Country", 
                "< $1.90",
                "< $3.20",
                "< $5.50",
                "Year",
                "Continent"]
df_1.info()  # Nos da una descripción general del dataframe

df_1.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Country    166 non-null    object
 1   < $1.90    166 non-null    object
 2   < $3.20    166 non-null    object
 3   < $5.50    166 non-null    object
 4   Year       166 non-null    int64 
 5   Continent  166 non-null    object
dtypes: int64(1), object(5)
memory usage: 7.9+ KB


Country < $1.90 < $3.20 < $5.50  Year      Continent
0    Albania   10.00   26.60   38.40  2019         Europe
1    Algeria    0.32    2.23   20.83  2019         Africa
2     Angola   51.40   72.79   89.13  2019         Africa
3  Argentina    1.60    5.80   18.20  2020  South America
4    Armenia    0.40    6.90   44.70  2020           Asia

9.	Transforma las columnas “< \\$1.90[1]”, “< \\$3.20[5]”, “< \\$5.50[6]” a tipo __flotante__ para que puedas hacer análisis con ellas. Para esto te recomendamos utilizar la función __“astype”__. Para más información te recomendamos entrar a el siguiente vínculo: 

https://www.geeksforgeeks.org/python-pandas-dataframe-astype/#:~:text=astype()%20method%20is%20used,type%20to%20another%20data%20type. 

In [33]:

df_1 = df_1.astype({"< $1.90":'float64',
                    "< $3.20":'float64',
                    "< $5.50":'float64'}) 
df_1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    166 non-null    object 
 1   < $1.90    166 non-null    float64
 2   < $3.20    166 non-null    float64
 3   < $5.50    166 non-null    float64
 4   Year       166 non-null    int64  
 5   Continent  166 non-null    object 
dtypes: float64(3), int64(1), object(2)
memory usage: 7.9+ KB


10. Utiliza la función __describe__ en el dataframe y responde __¿Cuál es el promedio del porcentaje de la población que vive con menos de $5,50 dólares al día?__	

In [34]:
print(df_1.describe())
# df['Poverty headcount ratio $2.15 a day'].describe() # Beetho OK o mean()
# En éste caso sería de la población que vive con menos de $6.85 al día, que es: 

print("Promedio de $6.85:", 34.010937)

# Otra forma de hacerlo
statistics = df_1.describe()

# Extraer el promedio de la columna '< $5.50[7]'
#mean_percentage = statistics['< $5.50[7]']['mean']

#mean_percentage

          < $1.90     < $3.20     < $5.50         Year
count  166.000000  166.000000  166.000000   166.000000
mean    12.956807   24.197048   38.735361  2019.018072
std     20.274184   28.958227   34.826700     1.146657
min      0.000000    0.000000    0.000000  2006.000000
25%      0.300000    0.835000    3.302500  2019.000000
50%      2.050000    9.155000   29.455000  2019.000000
75%     18.122500   42.187500   73.482500  2019.000000
max     80.710000   93.270000   98.440000  2021.000000
Promedio de $6.85: 34.010937


11.	__¿Cuál es el porcentaje máximo de personas que viven con menos de \\$1,90 dólares al día?__

In [36]:
# En éste caso sería de la población que vive con menos de $2.15 al día, que es: 
# df['Poverty headcount ratio $2.15 a day'].describe() # Beetho OK or .max()
#78.90
80.71

# Extraer el valor máximo de la columna '< $1.90[1][5]'
max_percentage = statistics['< $1.90']['max']
print(max_percentage)

80.71


12. __¿Cuál es el país que posee ese último porcentaje?__

In [39]:
P1_90 = df_1["< $1.90"]
indice = P1_90[P1_90 == 80.71]
pais2_15 = df_1.loc[indice.index[0]]
print("País con el máximo:" , pais2_15["Country"]) # Democratic Republic of the Congo

#max_index = df['< $1.90[1][5]'].idxmax()
#country_with_max_percentage = df.loc[max_index, 'Country']


País con el máximo: South Sudan


13.	__¿Cuál es el porcentaje de la población en México que gana menos de \\$1,90 dólares al día?__

In [41]:
# Una forma de hacerlo 
C2_15 = df_1["Country"]
indice = C2_15[C2_15 == "Mexico"]
porc = df_1.loc[indice.index[0]]
print("Porcentaje de población en México que gana menos de $1.90: ",porc["< $1.90"], "%")

# Otra forma de hacerlo
porc = df_1[df_1["Country"] == "Mexico"]["< $1.90"].values[0]
print(f"Porcentaje de población en México que gana menos de $1.90: ",porc, "%")

# Otra mas
#mexico_data = df_1[df_1['Country'] == 'Mexico']

# Obtener el porcentaje de la población en México que gana menos de $1,90 al día
#mexico_percentage = mexico_data['< $1.90[1][5]'].iloc[0]


Porcentaje de población en México que gana menos de $1.90:  3.1 %
Porcentaje de población en México que gana menos de $1.90:  3.1 %


14.	__¿Cuáles son los 5 países que tienen el mayor porcentaje de población que gana menos de \\$1,90 dólares al día?__

In [42]:
df_1.sort_values("< $1.90", ascending=False)[0:5]["Country"]

# OTra Forma
#top_5_countries = df.sort_values('< $1.90[1][5]', ascending=False).head(5)

#top_5_countries_list = top_5_countries[['Country', '< $1.90[1][5]']]

135                          South Sudan
20                               Burundi
87                            Madagascar
88                                Malawi
30     Congo, Democratic Republic of the
Name: Country, dtype: object

15.	Utiliza la función "drop" de "Pandas" para eliminar la columna "year" y así simplificar más tu conjunto de datos.

In [43]:
df_1 = df_1.drop(columns="Year",axis=1) # podría ser sin axis=1

df_1

Country  < $1.90  < $3.20  < $5.50      Continent
0      Albania    10.00    26.60    38.40         Europe
1      Algeria     0.32     2.23    20.83         Africa
2       Angola    51.40    72.79    89.13         Africa
3    Argentina     1.60     5.80    18.20  South America
4      Armenia     0.40     6.90    44.70           Asia
..         ...      ...      ...      ...            ...
161  Venezuela     6.70    14.30    32.70  South America
162    Vietnam     1.35     5.69    19.87           Asia
163      Yemen    54.69    81.99    94.55           Asia
164     Zambia    58.52    75.21    87.95         Africa
165   Zimbabwe    39.50    63.80    82.80         Africa

[166 rows x 5 columns]

16.	Utiliza la función “groupby” y contesta la siguiente pregunta __¿Cuál es el porcentaje promedio de la población en Sudamérica que vive con menos de \\$3,20 dólares al día?__

In [51]:
# OBSERVACION: El nuevo conjunto de datos ya no contiene región 
#               Sudamérica, ahora se llama "Latin America & Caribbean"

#sel = df_1.Region.str.contains('Latin')    # OTRA Forma de seleccionar la INFO
#df_latin = df_1.loc[sel]
#df_latin
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Imprime el DataFrame
print(df_1)

# Restaura las opciones a los valores predeterminados (opcional)
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

df3_20 = df_1[df_1["Continent"] == "South America"].groupby("Continent")["< $3.20"].mean()
df3_20.head()

                               Country  < $1.90  < $3.20  < $5.50  \
0                              Albania    10.00    26.60    38.40   
1                              Algeria     0.32     2.23    20.83   
2                               Angola    51.40    72.79    89.13   
3                            Argentina     1.60     5.80    18.20   
4                              Armenia     0.40     6.90    44.70   
5                            Australia     0.50     0.74     0.74   
6                              Austria     0.60     0.70     0.80   
7                           Azerbaijan     0.00     0.00     0.00   
8                           Bangladesh     6.62    37.44    76.01   
9                              Belarus     0.00     0.00     0.10   
10                             Belgium     0.10     0.10     0.20   
11                              Belize    14.39    28.99    53.77   
12                               Benin    43.38    70.53    89.54   
13                              Bh

Continent
South America    9.68
Name: < $3.20, dtype: float64

17.	__¿Cuál es el país que está en el lugar 140 de la lista?__

In [ ]:

df["Country"].iloc[139] # Porque empieza de "0"

'Suriname (Urban)'

18.	__¿Cuál es el país que posee el 140 como número de índice?__

In [ ]:

df["Country"].iloc[140] #.values[0]

'Sweden'

19.	__¿Cuál es el país de América del sur que tiene menos porcentaje de población ganando \\$1,90 dólares al día?__

In [56]:
df_1[df_1["Continent"] == "South America"].sort_values("< $1.90")[0:1]["Country"].values[0] #, ascending=False

'Uruguay'

20.	__¿Cuál es el país de América del sur que tiene más porcentaje de población ganando \\$1,90 dólares al día?__

In [57]:
df_1[df_1["Continent"] == "South America"].sort_values("< $1.90", ascending=False)[0:1]["Country"].values[0]

'Suriname (Urban)'

21.	__¿Cuál es el país de América del norte que tiene más porcentaje de población ganando \\$5,50 dólares al día?__

In [58]:
df_1[df_1["Continent"] == "North America"].sort_values("< $5.50", ascending=False)[0:1]["Country"].values[0]

'Haiti'

22.	__¿Cuál es el país de América del norte que tiene menos porcentaje de población ganando \\$3,20 dólares al día?__

In [59]:

df_1[df_1["Continent"] == "North America"].sort_values("< $3.20")[0:1]["Country"].values[0]

'Canada'

23.	Utiliza la función "to_csv" de "Pandas" para generar un archivo .csv con los datos trabajados. Ejemplo de la sintaxis de la función anterior: df.to_csv("NOMBRE.csv")

In [60]:
df_1.to_csv("economia.csv")

24. Guarda tu libreta, tu archivo csv recién creado y colócalos en una carpeta comprimida con extensión __.zip__. Sube el archivo .zip a la plataforma de EdX y califica los ejercicios de tus demás compañeros.
<img src="img3/Anáhuac_edX.png" width="498" height="150" align="center"/>